about/urls.py
from django.conf.urls import url

from about import views


urlpatterns = [
    # home page Liahne
    url(r'^$', views.intro_view, name='intro'),
]

page/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    # uvodne kecy, kontakt, demo, faq,...
    url(r'^', include('about.urls', namespace="about")),
    # zadania, riesenia uloh; sady
    url(r'^tasks/', include('tasks.urls', namespace="tasks")),
    # submity, statistiky
    url(r'^submits/', include('submit.urls', namespace="submit")),
    # django admin
    url(r'^admin/', include(admin.site.urls)),
    # login
    url(r'^account/', include('ksp_login.urls')),
]

tasks/urls.py
from django.conf.urls import url

from tasks import views

urlpatterns = [
    # tasks/    (aktualna sada usera)
    url(r'^$', views.task_set_graph_view, name='index'),
    # tasks/set/intro  (konkretna sada ako list)
    url(r'^set/(?P<pk>\w+)$', views.task_set_view, name='set'),
    # tasks/set/intro/graph    (konkretna sada ako graf)
    url(r'^set/(?P<pk>\w+)/graph$', views.task_set_graph_view, name='set_graph'),
    # tasks/popolvar   (zadanie ulohy/studijny text)
    url(r'^(?P<pk>\w+)$', views.task_view, name='task'),
    # tasks/popolvar/ex-sol    (vzorove riesenie ulohy)
    url(r'^(?P<pk>\w+)/ex-sol$', views.example_solution_view, name='example_solution'),
]

tasks/views.py
from datetime import datetime

import pygraphviz as pgv

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render

from submit import helpers
from submit.forms import TaskSubmitForm
from submit.models import Submit
from tasks.models import TaskSet, Task, Stalker, Active


@login_required
def task_set_view(request, pk):  # zobrazenie sady ako zoznam
    task_set = get_object_or_404(TaskSet, pk=pk)

    if not TaskSet.can_see(task_set, request.user):
        raise Http404

    # vytvori sa alebo updatne aktualna sada
    act = Active.objects.get_or_create(user=request.user)
    a = act[0]
    a.task_set = task_set
    a.save()

    # zoznam uloh v sade; iba tie, ktorym moze vidiet zadania v zozname
    q = Task.objects.filter(task_set=task_set)
    q_ids = [o.id for o in q if Task.can_see(o, request.user, 't')]
    tasks = q.filter(id__in=q_ids)

    # zoznam sad do horneho menu; iba tie, ktore user moze vidiet
    q = TaskSet.objects.order_by('title')
    q_ids = [o.id for o in q if TaskSet.can_see(o, request.user)]
    sets = q.filter(id__in=q_ids)

    # roztriedenie uloh na kategorie (ci su vyriesene/precitane)
    # v tomto poradi sa mu aj zobrazuju
    task_cat = []
    task_cat.append({'tasks': [], 'type': 'act_sub'})  # 0
    task_cat.append({'tasks': [], 'type': 'act_read'})  # 1
    task_cat.append({'tasks': [], 'type': 'sol_sub'})  # 2
    task_cat.append({'tasks': [], 'type': 'sol_read'})  # 3
    for task in tasks:
        if Task.is_solved(task, request.user):
            if task.type == Task.SUBMIT:
                task_cat[2]['tasks'].append(task)
            elif task.type == Task.READ:
                task_cat[3]['tasks'].append(task)
        elif Task.is_enabled(task, request.user):
            if task.type == Task.SUBMIT:
                task_cat[0]['tasks'].append(task)
            elif task.type == Task.READ:
                task_cat[1]['tasks'].append(task)

    return render(request, 'tasks/task_set.html',
                  {
                      'active_app': 'tasks',  # kvoli havnemu menu
                      'task_set': task_set,  # aktualna sada
                      'sets': sets,  # viditelne sady v taboch
                      'style': 'list',  # styl zobrazovania sady
                               'categories': task_cat,  # ulohy podla kategorii
                               'tasks': tasks,  # danej sady
                  },
                  )


@login_required
def task_set_graph_view(request, pk=False):  # zobrazenie sady ako graf

    # ak sme nespecifikovali sadu (menu->Ulohy), zobrazi sa/vytvori sa aktivna
    if not pk:
        act, _ = Active.objects.get_or_create(user=request.user)

        # In case the active task was hidden, set the default task as active.
        if not act.task.can_see(request.user, 'g') or not act.task_set.can_see(request.user):
            act.task_set = TaskSet.objects.get(id='intro')
            act.task = Task.objects.get(id='submit')
            act.save()

        pk = act.task_set.id

    task_set = get_object_or_404(TaskSet, pk=pk)

    if not TaskSet.can_see(task_set, request.user):
        raise Http404

    # vytvori sa alebo updatne aktualna sada
    act = Active.objects.get_or_create(user=request.user)

    a = act[0]
    a.task_set = task_set
    a.save()

    # zoznam uloh v sade; iba tie, o ktorych moze vediet

    q = Task.objects.filter(task_set=task_set)
    q_ids = [o.id for o in q if Task.can_see(o, request.user, 'g')]
    tasks = q.filter(id__in=q_ids)

    # zoznam sad do horneho menu; iba tie, ktore user moze vidiet
    q = TaskSet.objects.order_by('title')
    q_ids = [o.id for o in q if TaskSet.can_see(o, request.user)]
    sets = q.filter(id__in=q_ids)

    # roztriedime kvoli vykreslovaniu v grafe
    solved_tasks = []
    actual_tasks = []
    invis_tasks = []
    for task in tasks:
        if Task.is_solved(task, request.user):
            solved_tasks.append(task)
        elif Task.is_enabled(task, request.user):
            actual_tasks.append(task)
        else:
            invis_tasks.append(task)

    #nakrmime graf datami
    G = pgv.AGraph(directed=True)
    G.node_attr['color'] = '#dddddd'
    G.node_attr['style'] = 'filled'
    G.node_attr['fontcolor'] = '#ffffff'
    G.node_attr['fontname'] = 'Helvetica, Arial, sans-serif'
    G.graph_attr['bgcolor'] = 'transparent'
    G.edge_attr['color'] = '#555555'
    G.edge_attr['arrowhead'] = 'open'

    RED = '#C71C22'
    BLUE_L = '#2FA4E7'
    BLUE_D = '#033C73'
    GREEN = '#73A839'
    ORANGE = '#DD5600'

    for task in solved_tasks:
        G.add_node(task.id,
                   fillcolor = (GREEN if (task.type == Task.SUBMIT) else BLUE_D),
                   shape = ('ellipse' if (task.type == Task.SUBMIT) else 'box'),
                   tooltip = task.title,
                   URL = reverse('tasks:task', args=(task.id,)),
                   fontcolor = '#eeeeee'
                   )

    for task in actual_tasks:
        G.add_node(task.id,
                   fillcolor = (RED if (task.type == Task.SUBMIT) else BLUE_L),
                   shape = ('ellipse' if (task.type == Task.SUBMIT) else 'box'),
                   tooltip = task.title,
                   URL = reverse('tasks:task', args=(task.id,)),
                   fontcolor = '#ffffff'
                   )

    for task in invis_tasks:
        #admin si vie pozerat aj invis ulohy
        if request.user.is_active and request.user.is_staff:
            G.add_node(task.id,
                    fillcolor = '#ffffff',
                    shape = ('ellipse' if (task.type == Task.SUBMIT) else 'box'),
                    tooltip = task.title,
                    URL = reverse('tasks:task', args=(task.id,)),
                    fontcolor = '#000000'
                    )
        else:
            G.add_node(task.id,
                    label = '',
                    fillcolor = '#FFFFFF',
                    shape = ('ellipse' if (task.type == Task.SUBMIT) else 'box'),
                    tooltip = ' ',
                    fontcolor = 'black',
                    style = 'dashed',
                    color = '#333333'
                    )

    #najprv trebalo pridat vsetky vrcholy, aby sa im nastavil styl, hrany az potom
    for task in solved_tasks:
        edges = task.prereqs.all()
        for edge in edges:
            G.add_edge(edge.id, task.id, style='solid')

    for task in actual_tasks:
        edges = task.prereqs.all()
        for edge in edges:
            G.add_edge(edge.id, task.id, style='solid')

    for task in invis_tasks:
        edges = task.prereqs.all()
        for edge in edges:
            G.add_edge(edge.id, task.id, style='dashed')

    G.layout()

    #vymazeme hlavicky, lebo neincludujeme svg object, ale rovno ho kreslime; inak by sme neboli html valid
    graph = '\n'.join(G.draw(format='svg').split('\n')[3:])

    return render(request, 'tasks/task_set_graph.html',
                  {
                      'graph':graph, #data pre graf (svg)
                      'active_app': 'tasks',  # hlavne menu
                      'task_set': task_set,  # aktualna sada
                      'sets': sets,  # vsetky sady
                      'style': 'graph',  # styl zobrazovania sady
                  },
                  )


@login_required
def task_view(request, pk):  # zadanie ulohy
    task = get_object_or_404(Task, pk=pk)

    if not Task.can_see(task, request.user, 't'):
        raise Http404

    # vytvorime alebo updatneme aktivnu ulohu
    act = Active.objects.get_or_create(user=request.user)
    if task.type == task.SUBMIT:
        a = act[0]
        a.task = task
        a.save()

    # ak sa submitovalo
    error = False
    if request.method == 'POST':
        form = TaskSubmitForm(request.POST, request.FILES)
        if form.is_valid():
            submit_id = helpers.process_submit(
                request.FILES['submit_file'],
                task,
                form.cleaned_data['language'],
                request.user)
            if submit_id[0]:
                return HttpResponseRedirect(reverse('submit:protocol', args=(submit_id[1],)) + '#protocol')
            else:
                error = submit_id[1]
        else:
            error = 'file-error'

    # pridame seen
    stalker = Stalker(user=request.user, task=task, seen=datetime.now())
    stalker.save()

    form = TaskSubmitForm()
    submits = Submit.objects.filter(task=pk, user=request.user).order_by('-timestamp')
    is_solved = Task.is_solved(task, request.user)

    return render(request, 'tasks/task.html',
                  {
                      'active_app': 'tasks',  # hlavne menu
                      'active': 'text',  # ci si pozerame zadanie alebo vzorak
                      'is_solved': is_solved,  # kvoli linku v taboch
                      'task': task,
                      'form': form,  # submitovaci formular
                      'submits': submits,  # doterajsie submity v ulohe
                      'error': error,  # chyba suboru / nepodarene pripojenie na testovac
                      'req_user': request.user,  # momentalne lognuty (kvoli odkazu na riesenie pre adminov)
                  },
                  )


@login_required
def example_solution_view(request, pk):  # vzorak
    task = get_object_or_404(Task, pk=pk)

    if not Task.can_see(task, request.user, 's'):
        raise Http404

    if task.type == task.READ:
        raise Http404

    return render(request, 'tasks/example_solution.html',
                  {
                      'is_solved': Task.is_solved(task, request.user),  # kvoli linku v taboch
                      'active_app': 'tasks',  # hlavne menu
                      'active': 'ex_sol',  # ci sa zobrazuje zadanie alebo vzorak
                      'task': task,
                  },

tasks/templates/tasks/example_solution.html
{% extends "base.html" %}
{% load widgets %}
{% block title %}{{ task.title }} (riešenie){% endblock title %}

{% block content %}
{% if task.is_public|is_false %} <div class = "non-public">{% endif %}
    {% include 'tasks/task_header.html' %}
    <div class = "col-lg-7">
        {{ task.example_solution|safe }}
    </div>
{% if task.is_public|is_false %} <div class = "non-public">{% endif %}
{% endblock content %}

tasks/templates/tasks/task.html
{% extends "base.html" %}
{% load widgets %}
{% block title %}{{ task.title }} (zadanie){% endblock title %}
{% block content %}
{% if task.is_public|is_false %} <div class = "non-public">{% endif %}
   {% include 'tasks/task_header.html' %}
    <div class = "row">
        <div class = "col-lg-7">
            {{ task.rendered_text|safe }}
        </div>
        {% if task.type == task.SUBMIT %}
            <div class = "col-lg-5">
                <div class = "col-lg-12" id = "submit">
                    {% if error %}
                        {% if error == "file-error" %}
                            <div class="alert alert-dismissable alert-danger">
                                <button type="button" class="close" data-dismiss="alert">×</button>
                                Nastala chyba pri submite - <strong>nenačítal sa súbor</strong> alebo <strong>nepasuje koncovka</strong>.
                            </div>
                        {% elif error == "connect-error" %}
                            <div class="alert alert-dismissable alert-danger">
                                <button type="button" class="close" data-dismiss="alert">×</button>
                                Z nejakého dôvodu sa <strong>nepodarilo pripojiť na testovač</strong>. Prosíme, <a href = "{% url 'about:intro' %}#contact" class = "alert-link">kontaktuj nás</a>.
                            </div>
                        {% else %}
                            <div class="alert alert-dismissable alert-danger">
                                <button type="button" class="close" data-dismiss="alert">×</button>
                                Nastala bližšie neznáma chyba.
                            </div>
                        {% endif %}
                    {% endif %}
                        {% include "submit/send_solution.html" %}
                </div>
                <div class = "col-lg-12">
                    {% include "submit/submits_user_task.html" %}
                </div>
            </div>
        {% endif %}
    </div>
{% if task.is_public|is_false %} </div>{% endif %}
{% endblock %}

tasks/templates/tasks/task_header.html
<!-- <div class = "page-header"> -->
{% if task.type == task.SUBMIT %}
    <h2>{{ task.title }} ({{ task.id }})</h2>
    <ul class="nav nav-tabs">
        <li {% if active == 'text' %} class = "active" {% endif %}><a href = "{% url 'tasks:task' task.id %}"><span class="glyphicon glyphicon-pencil"></span>&nbsp;Zadanie</a></li>

        <li {% if active == 'ex_sol' %}
                class = "active"
            {% elif not is_solved %}
                {% if not req_user.is_active or not req_user.is_staff %}
                    class = "disabled"
                {% endif %}
            {% endif %}
            >

            {% if is_solved %}
                <a href = "{% url 'tasks:example_solution' task.id %}"><span class="glyphicon glyphicon-ok"></span>&nbsp;
            {% else %}
                <a{% if req_user.is_staff and req_user.is_active %} href = "{% url 'tasks:example_solution' task.id %}"{% endif %}><span class="glyphicon glyphicon-remove"></span>&nbsp;
            {% endif %}
            Riešenie</a>
        </li>
        <li><a href = "{% url 'submit:task' task.id %}"><span class="glyphicon glyphicon-check"></span>&nbsp;Úspešní riešitelia ({{ task.num_solvers }})</a></li>
     </ul>
     <br />
{% elif task.type == task.READ %}
    <div class = "page-header">
        <h2>{{ task.title }}</h2>
    </div>
{% endif %}
<!--        <li><a href = "{% url 'submit:task' task.id %}">Štatistika</a></li>
    </ul>
    <br />-->
<!-- </div> -->

tasks/templates/tasks/task_set.html
{% extends "base.html" %}
{% load widgets %}
{% block title %}{{ task_set.title }}{% endblock %}

{% block content %}
{% if task_set.public|is_false %} <div class = "non-public">{% endif %}
    {% include 'tasks/task_set_header.html' %}
    <div class = "row">
        {% for cat in categories %}
            {% if cat.tasks %}
                <div class = "col-lg-3">
                    <div class = "panel
                        {% if cat.type == 'act_sub' %}panel-danger
                        {% elif cat.type == 'act_read' %}panel-primary
                        {% elif cat.type == 'sol_sub' %}panel-success
                        {% elif cat.type == 'sol_read' %}panel-info
                        {% endif %}">
                        <div class = "panel-heading">
                            <h4 class = "panel-title">
                                {% if cat.type == 'act_sub' %}
                                    <span class="glyphicon glyphicon-question-sign"></span>&nbsp;Aktuálne úlohy
                                {% elif cat.type == 'act_read' %}
                                    <span class="glyphicon glyphicon-ok-sign"></span>&nbsp;Neprečítané texty
                                {% elif cat.type == 'sol_sub' %}
                                    <span class="glyphicon glyphicon-ok-sign"></span>&nbsp;Vyriešené úlohy
                                {% elif cat.type == 'sol_read' %}
                                    <span class="glyphicon glyphicon-flag"></span>&nbsp;Prečítané texy
                                {% endif %}
                                ({{ cat.tasks|length }})
                            </h4>
                        </div>
                        <div class = "panel-body">
                            <table class = "table table-hover table-striped">
                                <thead>
                                    <tr>
                                        {% if cat.type == 'act_sub' or cat.type == 'sol_sub' %}
                                            <th>Úloha</th><th>Vyriešilo</th>
                                        {% elif cat.type == 'act_read' or cat.type == 'sol_read' %}
                                            <th>Text</th>
                                        {% endif %}
                                    </tr>
                                </thead>
                                <tbody>{% for task in cat.tasks %}
                                    <tr{% if task.public|is_false %} class = "non-public"{% endif %}>
                                        <td><a href= "{% url 'tasks:task' task.id %}">{{ task.title }}</a></td>
                                        {% if cat.type == 'act_sub' or cat.type == 'sol_sub' %}
                                            <td>{{ task.num_solvers }}</td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}</tbody>
                            </table>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% if task_set.public|is_false %}</div>{% endif %}

{% endblock content %}

tasks/templates/tasks/task_set_graph.html
{% extends "base.html" %}

{% load staticfiles widgets %}
{% block title %}{{ task_set.title }}{% endblock %}

{% block content %}
    {% if not task_set.public %}<div class = "non-public">{% endif %}
        {% include 'tasks/task_set_header.html' %}
        <div class="row">
            {{ graph|safe }}
        </div>
    {% if not task_set.public %}</div>{% endif %}
{% endblock content %}

tasks/templates/tasks/task_set_header.html
<div class = "row">
{% load widgets %}
    <ul class="nav nav-tabs">
        {% for set in sets %}
            <li {% if task_set == set %} class = "active" {% endif %}><a {% if set.public|is_false %} class = "non-public" {% endif %} href= "{% url 'tasks:set' set.id %}{% if style == 'graph' %}/graph{% endif %}">{{ set.id }}</a></li>
        {% endfor %}
    </ul>
</div>
<h2>
    <span class="btn-group">
        <button type="button" class="btn btn-default {% if style == 'graph' %}active{% endif %}" onclick="location.href='{% url 'tasks:set' task_set.id %}/graph';">
            <span class="glyphicon glyphicon-ok-sign" style = "font-size: 0.7em;"></span>
            <span class="glyphicon glyphicon-arrow-right" style = "font-size: 0.7em;"></span>
            <span class="glyphicon glyphicon-question-sign" style = "font-size: 0.7em;"></span>
        </button>
        <button type="button" class="btn btn-default {% if style == 'list' %}active{% endif %}" onclick="location.href='{% url 'tasks:set' task_set.id %}';">
            &nbsp;&nbsp;<span class="glyphicon glyphicon-th-list"></span>&nbsp;&nbsp;
        </button>
    </span>
    {{ task_set.title }}
</h2>
<hr />
<br />