page/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    # uvodne kecy, kontakt, demo, faq,...
    url(r'^', include('about.urls', namespace="about")),
    # zadania, riesenia uloh; sady
    url(r'^tasks/', include('tasks.urls', namespace="tasks")),
    # submity, statistiky
    url(r'^submits/', include('submit.urls', namespace="submit")),
    # django admin
    url(r'^admin/', include(admin.site.urls)),
    # login
    url(r'^account/', include('ksp_login.urls')),
]

submit/urls.py
from django.conf.urls import url

from submit import views


urlpatterns = [
    # submits/protocol/2/ (detaily submitu)
    url(r'^protocol/(?P<pk>\d+)/$', views.protocol_view, name='protocol'),

    # submits/update
    url(r'^update/$', views.update_submit),

    # submits/   (vsetky moje)
    url(r'^$', views.judge_view, {'type': 'me'}, name='index'),

    # submits/now    (teraz na testovaci)
    url(r'^now/$', views.judge_view, {'type': 'now'}, name='now'),

    # submits/task/popolvar   (vsetky uspesne v ulohe)
    url(r'^task/(?P<task>\w+)/$', views.judge_view, {'type': 'task'}, name='task'),

    # admin vidi aj:
    # submits/user/fero  (vsetky user-ove)
    url(r'^user/(?P<user>\w+)/$', views.judge_view, {'type': 'user'}, name='user'),

    # submits/user/fero/task/popolvar    (vsetky user-ove v ulohe)
    url(r'^user/(?P<user>\w+)/task/(?P<task>\w+)/$', views.judge_view, {'type': 'user_task'}, name='user_task'),
]

submit/models.py
# -*- coding: utf8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings


class Submit(models.Model):
    OK = 'OK'
    QUEUE = 'In queue...'

    STATS = {
        'OK': OK,
        'QUEUE': QUEUE,
        'WA': 'Wrong answer',
        'TO': 'Time limit exceeded',
        'IN': 'Internal error',
        'CE': 'Compilation error',
        'RE': 'Runtime exception',
        'SE': 'Security exception',
    }

    LANGUAGE_CHOICES = (
        (".", "Zisti podľa prípony"),
        (".cc", "C++ (.cpp/.cc)"),
        (".pas", "Pascal (.pas/.dpr)"),
        (".c", "C (.c)"),
        (".py", "Python 2.5 (.py)"),
        (".py3", "Python 3.1 (.py3)"),
        (".hs", "Haskell (.hs)"),
        (".cs", "C# (.cs)"),
        (".java", "Java (.java)")
    )

    EXTMAPPING = {
        ".cpp": ".cc",
        ".cc": ".cc",
        ".pp": ".pas",
        ".pas": ".pas",
        ".dpr": ".pas",
        ".c": ".c",
        ".py": ".py",
        ".py3": ".py3",
        ".hs": ".hs",
        ".cs": ".cs",
        ".java": ".java"
    }

    user = models.ForeignKey(settings.AUTH_USER_MODEL)  # clovek
    task = models.ForeignKey('tasks.Task')  # uloha
    timestamp = models.DateTimeField(  # cas submitu
        auto_now_add=True
    )
    message = models.CharField(  # pekna sprava z testovaca (nie skratka)
        max_length=256,
        default=QUEUE
    )
    scores = models.FloatField(  # ak je uloha na body
        blank=True,
        null=True
    )
    runtime = models.IntegerField(  # cas behu
        blank=True,
        default=-1,
        null=True
    )
    memory = models.IntegerField(  # spotreba pamate
        blank=True,
        default=-1,
        null=True
    )
    language = models.CharField(  # progr. jazyk
        max_length=20,
        choices=LANGUAGE_CHOICES
    )
    log = models.TextField(  # detailny na vstupy
        default=""
    )

    def __unicode__(self):
        return '%s | %s | %s | %s' % (
            self.user, self.task, self.timestamp.strftime('%d-%m-%Y %H:%M:%S'), self.message)

submit/forms.py
from django import forms

from submit.models import Submit


class TaskSubmitForm(forms.Form):
    submit_file = forms.FileField(max_length=100000)
    language = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'form-control'}),
        label='Jazyk',
        choices=Submit.LANGUAGE_CHOICES
    )

submit/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, Http404
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404, render

from tasks.models import Task, Active
from submit.models import Submit


@login_required
# rozne filtre na tabulku submitov; podla 'type'
def judge_view(request, type, task='', user=''):
    # defaultne hodnoty pre parametre do returnu
    cur_task = ''
    cur_user = ''
    tasks = ''

    if type == 'me':  # moje
        submits = Submit.objects.filter(
            user=request.user).order_by('-timestamp')

    elif type == 'now':  # aktualne
        submits = Submit.objects.order_by('-timestamp')[:10]

    elif type == 'task':  # vsetky uspesne v ulohe
        submits = Submit.objects.filter(
            task=task, message=Submit.OK).order_by('-timestamp')
        cur_task = get_object_or_404(Task, pk=task)
        if request.user.is_staff and request.user.is_active:
            tasks = Task.objects.filter(type=Task.SUBMIT)
        else:
            q = Task.objects.filter(public=True, type=Task.SUBMIT)
            q_ids = [o.id for o in q if o.task_set.public]
            tasks = q.filter(id__in=q_ids)

    # iba pre adminov:
    elif (request.user.is_staff and request.user.is_active):
        if type == 'user':  # vsetky userove
            cur_user = get_object_or_404(User, username=user)
            submits = Submit.objects.filter(
                user=cur_user).order_by('-timestamp')

        elif type == 'user_task':  # vsetky userove v ulohe
            cur_user = get_object_or_404(User, username=user)
            submits = Submit.objects.filter(
                user=cur_user, task=task).order_by('-timestamp')
            cur_task = get_object_or_404(Task, pk=task)
            tasks = Task.objects.all()

    else:
        raise Http404

    # aktivna uloha sa defaultne zobrazi vo filtri podla ulohy
    act = Active.objects.get_or_create(user=request.user)
    active_task = act[0].task.id

    return render(request, 'submit/judge.html',
                  {
                      'active_app': 'submit',  # kvoli menu hore
                      'submits': submits,  # tabulka submitov
                      'type': type,  # typ filtra
                      'tasks': tasks,  # viditelne ulohy pre search-box podla ulohy
                      'cur_task': cur_task,  # filtre podla ulohy
                      'cur_user': cur_user,  # filtre podla cloveka
                      'req_user': request.user,  # prihlaseny user
                      'active_task': active_task,  # aktivna uloha
                  },
                  )


@login_required
def protocol_view(request, pk):  # protokol z testovania
    submit = get_object_or_404(Submit, pk=pk)

    # ak si ho chce pozriet cudzi user, ktory nie je admin
    if not ((request.user.is_active and request.user.is_staff) or submit.user == request.user):
        raise Http404

    source_path = settings.PROJECT_PATH + '/../submit/submits/' + \
        str(submit.user.username) + '/' + str(submit.task.id) + '/' + str(submit.id) + '.data'

    source_code = open(source_path, 'r').read()

    return render(request, 'submit/protocol.html',
                  {
                      # 'active_app':'submit',
                      'submit': submit,
                      'source_code': source_code,
                  },
                  )


@csrf_exempt
def update_submit(request):  # spracovanie submitu po odpovedi testovaca
    if (request.method == 'POST'):
        # data z testovaca k sebe do db
        id = request.POST['submit_id']

        submit = get_object_or_404(Submit, pk=id)

        message = request.POST['result']
        # slovny popis (WA -> Wrong answer)
        if message in Submit.STATS:
            submit.message = Submit.STATS[message]
        else:
            submit.message = message

        submit.runtime = request.POST['time']
        submit.memory = request.POST['memory']
        submit.log = request.POST['log']

        submit.save()
    return HttpResponse("Ty si chudak")

submit/templates/submit/judge.html
{% extends "base.html" %}
{% block title %}Submity{% endblock title %}
{% block content %}
{% load items_format %}
{% include 'submit/submits_header.html' %}
{% load tz %}

<div class="panel panel-info">
    <div class="panel-heading">
        {% if type == 'me' %}
            <h4 class="panel-title">Všetky moje submity</h4>
        {% elif type == 'now' %}
            <h4 class="panel-title">Najčerstvejšie výsledky z testovača</h4>
        {% elif type == 'task' %}
            <div class = "row" style = "margin-left:0; margin-left:0;" >
                <div class = "pull-left">
                    <h4 class="panel-title" style = "padding-top:10px;" >Úspešné submity úlohy <i>{{ cur_task|task_format }}</i></h4>
                </div>
                <select id="select-search" onchange = "location = this.options[this.selectedIndex].value;" class="col-lg-4">
                   {% regroup tasks by task_set as task_list %}
                        <option value="">Začni písať názov úlohy...</option>
                   {% for task in task_list %}
                        <optgroup label="{{ task.grouper }}">
                            {% for item in task.list %}
                                <option value="{% url 'submit:task' item.id %}#submits">{{ item.title }} ({{ item.id }})</option>
                            {% endfor %}
                        </optgroup>
                    {% endfor %}
                </select>
            </div>
        {% elif type == 'user' %}
            <h4 class="panel-title">Všetky submity človeka <b>{{ cur_user|user_format }}</b>&nbsp;&nbsp;&nbsp;<i class = "text-muted">(parametre sa menia intuitívne hore v linku)</i></h4>
        {% elif type == 'user_task' %}
            <h4 class="panel-title">Všetky submity človeka <b>{{ cur_user|user_format }}</b> v úlohe <i>{{ cur_task|task_format }}</i>&nbsp;&nbsp;&nbsp;<i class = "text-muted">(parametre sa menia intuitívne hore v linku)</i> </h4>
        {% endif %}
    </div>
    <div class = "panel-body">
        <table class="table table-striped table-hover ">
            <thead>
                <tr>
                    <th>Čas</th>
                    <th>Meno</th>
                    <th>Úloha</th>
                    <th>Jazyk</th>
                    <th>Výsledok</th>
                    <th>Detaily</th>
                </tr>
            </thead>
            <tbody>
                {% for submit in submits %}
                <tr>
                    <td>{{ submit.timestamp|timestamp_format }}</td>
                    <td>{{ submit.user|user_format }}</td>
                    <td>{{ submit.task|task_format }}</td>
                    <td>{{ submit.language|language_format }}</td>
                    <td>{{ submit.message|message_format }}</td>
                    <td>{% if req_user.is_active and req_user.is_staff or req_user == submit.user %}{{ submit.id|detail_format }}{% endif %}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content%}

submit/templates/submit/protocol.html
{% extends "base.html" %}
{% load items_format %}
{% block content %}
    <div class = "page-header">
    <a name="protocol"></a>
    <h2>Protokol z testovania</h2>
    </div>
        <table class="table table-striped table-hover ">
            <thead>
                <tr>
                    <th>Čas</th>
                    <th>Meno</th>
                    <th>Úloha</th>
                    <th>Jazyk</th>
                    <th>Výsledok</th>
                    <th>Čas behu</th>
                    <th>Spotreba pamäte</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ submit.timestamp|timestamp_format }}</td>
                    <td>{{ submit.user|user_format }}</td>
                    <td>{{ submit.task|task_format }}</td>
                    <td>{{ submit.language|language_format }}</td>
                    <td>{{ submit.message|message_format }}</td>
                    <td>{{ submit.runtime|runtime_format }}</td>
                    <td>{{ submit.memory|memory_format }}</td>
                </tr>
            </tbody>
        </table>

<div class = "col-lg-5">
    <h3>Výsledky testovania:</h3>
    {% if submit.message == submit.QUEUE %}
        <p>Testovanie môže pár chvíľ trvať. Občas skús refresh stránky.</p>
        <div class="progress progress-striped active">
            <div class="progress-bar" style="width: 100%"></div>
        </div>
    {% else %}
        {{ submit.log|log_format }}
    {% endif %}
</div>
<div class = "col-lg-7">
    <h3>Odovzdaný program:</h3>
    <pre class = "prettyprint">{{ source_code }}</pre>
</div>
{% endblock content %}

submit/templates/submit/send_solution.html
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Odovzdaj riešenie</h3>
    </div>
    <div class="panel-body">
        <form enctype="multipart/form-data" method="post" action="#submit" class="form-horizontal">
            {% csrf_token %}
            {{ form.as_p }}
            <div class = "col-lg-12">
                <input type="submit" class="btn btn-primary" value="Submit" />
            </div>
        </form>
    </div>
</div>

submit/templates/submit/submits_header.html
{% load items_format %}
<a name="submits"></a>

<!-- <p>Reklama: Nedostal si ešte ani jedno {{ "OK"|message_format }} a netušíš, čo robíš zle? Položka "Pomoc" v menu je tu presne na to! (A ak ani tá nepomôže, treba sa opýtať.)</p> -->
<ul class="nav nav-tabs">
    {% if type == "me" %}<li class="active">{% else %}<li>{% endif %}<a href="{% url 'submit:index' %}"><span class="glyphicon glyphicon-user"></span>&nbsp;Moje</a></li>

    {% if type == "now" %}<li class="active">{% else %}<li>{% endif %}<a href="{% url 'submit:now' %}"><span class="glyphicon glyphicon-time"></span>&nbsp;Aktuálne</a></li>

    {% if type == "task"%}<li class="active">{% else %}<li>{% endif %}
            <a href="{% url 'submit:task' active_task %}"><span class="glyphicon glyphicon-check"></span>&nbsp;Úspešní riešitelia úlohy...</a>
    </li>
    {% if req_user.is_staff and req_user.is_active %}
        {% if type == "user"%}<li class="active">{% else %}<li>{% endif %}
                <a href="{% url 'submit:user' req_user%}"><span class="glyphicon glyphicon-user"></span>&nbsp;Všetky submity riešiteľa...</a>
        </li>
        {% if type == "user_task"%}<li class="active">{% else %}<li>{% endif %}
                <a href="{% url 'submit:user_task' req_user active_task %}"><span class="glyphicon glyphicon-user"></span><span class="glyphicon glyphicon-tasks"></span>&nbsp;Všetky submity riešiteľa... v úlohe...</a>
    </li>
    {% endif %}
</ul>

submit/templates/submit/submits_user_task.html
{% load items_format %}
<div class="panel panel-info">
    <div class="panel-heading">
        <h4 class="panel-title">Tvoje submity</h4>
    </div>
    <div class = "panel-body">
        <table class="table table-striped table-hover ">
            <thead>
                <tr>
                    <th>Čas</th>
                    <th>Jazyk</th>
                    <th>Výsledok</th>
                </tr>
            </thead>
            <tbody>
                {% for submit in submits %}
                <tr>
                    <td>{{ submit.timestamp|timestamp_format }}</td>
                    <td>{{ submit.language|language_format }}</td>
                    <td>{{ submit.message|message_format }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>