about/urls.py
from django.conf.urls import url

from about import views


urlpatterns = [
    # home page Liahne
    url(r'^$', views.intro_view, name='intro'),
]

page/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    # uvodne kecy, kontakt, demo, faq,...
    url(r'^', include('about.urls', namespace="about")),
    # zadania, riesenia uloh; sady
    url(r'^tasks/', include('tasks.urls', namespace="tasks")),
    # submity, statistiky
    url(r'^submits/', include('submit.urls', namespace="submit")),
    # django admin
    url(r'^admin/', include(admin.site.urls)),
    # login
    url(r'^account/', include('ksp_login.urls')),
]

tasks/urls.py
from django.conf.urls import url

from tasks import views

urlpatterns = [
    # tasks/    (aktualna sada usera)
    url(r'^$', views.task_set_graph_view, name='index'),
    # tasks/set/intro  (konkretna sada ako list)
    url(r'^set/(?P<pk>\w+)$', views.task_set_view, name='set'),
    # tasks/set/intro/graph    (konkretna sada ako graf)
    url(r'^set/(?P<pk>\w+)/graph$', views.task_set_graph_view, name='set_graph'),
    # tasks/popolvar   (zadanie ulohy/studijny text)
    url(r'^(?P<pk>\w+)$', views.task_view, name='task'),
    # tasks/popolvar/ex-sol    (vzorove riesenie ulohy)
    url(r'^(?P<pk>\w+)/ex-sol$', views.example_solution_view, name='example_solution'),
]

templates/base.html
{% load tz %}
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        {% load staticfiles %}

        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}" type="text/css"/>
        <link rel="stylesheet" href="{% static 'google-code-prettify/prettify.css' %}" type="text/css"/>
        <link rel="stylesheet" href="{% static 'selectize/dist/css/selectize.bootstrap3.css' %}" data-theme="bootstrap3">
        <link rel="stylesheet" href="{% static 'own-style/own.css' %}" data-theme="bootstrap3">
        <link rel="stylesheet" href="{% static 'ksp_login/css/base.css' %}" type="text/css" />

        <title>Programátorská liaheň | {% block title %}{% endblock title %}</title>

    </head>
    <body>
        {% include "header.html" %}
        {% include "menu.html" %}
        <div class = "container">
            {% block ksp_login_title %}{% endblock ksp_login_title %}
            {% block content %}<p>Default content</p>{% endblock content %}
        </div>
        {% include "footer.html" %}

        <script src="{% static 'other-js/jquery-1.10.2.min.js' %}"></script>
        <script src="{% static 'file-input/bootstrap.file-input.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'other-js/bootswatch.js' %}"></script>
        <script>$(document).ready(function(){$('input[type=file]').bootstrapFileInput();});</script>

        <script src = "{% static 'google-code-prettify/prettify.js' %}"></script>
        <script>
            !function ($) {
                $(function(){
                window.prettyPrint && prettyPrint()
                })
            }(window.jQuery)
        </script>


        <script type="text/javascript" src="{% static 'selectize/dist/js/standalone/selectize.js' %}"></script>
        <script>
            $('#select-search').selectize({
                sortField: 'text'
            });
        </script>

        {% include "ksp_login/parts/include_javascript.html" %}

        <script>
            $('form :input[type=text]').addClass("form-control");
            $('form :input[type=email]').addClass("form-control");
            $('form :input[type=password]').addClass("form-control");
            $('.errorlist').addClass("alert alert-danger");
            $('.helptext').addClass("text-info");
        </script>

        <!--script>
            function escapeHtml(text) {
                return text
                    .replace(/&/g, "&amp;")
                    .replace(/</g, "&lt;")
                    .replace(/>/g, "&gt;")
                    .replace(/"/g, "&quot;")
                    .replace(/'/g, "&#039;");
            }
        </script-->

        <script type="text/javascript"
            src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
        </script>

        <script type="text/x-mathjax-config">
            MathJax.Hub.Config({
                tex2jax: {
                    inlineMath: [ ['$','$'], ["\\(","\\)"] ],
                    processEscapes: true
                }
            });
        </script>

    </body>
</html>

templates/footer.html
<br /><br />
<hr />
<div class = "container">
    <footer class="row">
        <div class="col-lg-12">
            <br />
            <p class = "text-center"><a href = "http://trojsten.sk"><span class="glyphicon glyphicon-play"></span>&nbsp;Trojsten</a>, <a href="http://ksp.sk">KSP</a> &copy; 2014&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
            <!--Powered by <a href="https://www.djangoproject.com/">Django</a>.
            Designed with <a href="http://bootswatch.com/">Bootstrap theme</a>.&nbsp;-->
            <a href = "{% url 'about:intro' %}#terms" ><span class="glyphicon glyphicon-file"></span>&nbsp;Podmienky</a>&nbsp;
            <a href = "{% url 'about:intro' %}#contact" ><span class="glyphicon glyphicon-phone-alt"></span>&nbsp;Kontakt</a>
            </p>
            <br />
        </div>
    </footer>
</div>

templates/header.html
<!--h1>Programatorska liahen 2.0</h1-->

templates/menu.html
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'about:intro' %}">Programátorská liaheň</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
            <li {% if active_app == 'tasks' %}class = "active"{% endif %}><a href="{% url 'tasks:index' %}"><span class="glyphicon glyphicon-tasks"></span>&nbsp;Úlohy</a></li>
            <li {% if active_app == 'submit' %}class = "active"{% endif %}><a href="{% url 'submit:index'%}"><span class="glyphicon glyphicon-envelope"></span>&nbsp;Submity</a></li>
            <li><a href=""><span class="glyphicon glyphicon-certificate"></span>&nbsp;Achievementy</a></li>
        </ul>
        {% include "ksp_login/parts/login_box.html" %}
        <ul class="nav navbar-nav navbar-right">
            <li><a href = "{% url 'about:intro' %}#contact" ><span class="glyphicon glyphicon-phone-alt"></span>&nbsp;Kontakt</a></li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;</li>
        </ul>

    </div><!-- /.navbar-collapse -->
  </div>
</nav>